trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pandas scikit-learn
    displayName: 'Install dependencies'

  - script: |
      pip install flake8
      flake8 train.py
    displayName: 'Lint code'

  - script: |
      python train.py
    displayName: 'Run tests'

  - script: |
      echo "Deploying model..."
    displayName: 'Deploy model'
