trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m flake8 your_code.py  # Adjust with your actual code file or path
  displayName: 'Lint code'

- script: |
    python -m unittest discover -s tests  # Adjust with your test directory
  displayName: 'Run tests'

- script: |
    echo "Deploying model..."
    # Add your deployment commands here
  displayName: 'Deploy model'